name: CI Módulo 26 - PactumJS

on:
  push:
    branches: [ "main" ] # Verifique se o nome da sua branch é main ou master
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalando o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalando as dependências
        run: npm install

      - name: Rodando os testes do Módulo 24
        run: npm test